---
include:
  # Zeph
  - board: nice_nano_v2
    shield: zeph_left
  - board: nice_nano_v2
    shield: zeph_right

  # Cosmos
  - board: nice_nano_v2
    shield: cosmos_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: cosmos_right
    # snippet: studio-rpc-usb-uart
    # cmake-args: -DCONFIG_ZMK_STUDIO=y

  # Corne
  - board: nice_nano_v2
    shield: corne_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: corne_right

  # Caldera
  - board: nice_nano_v2
    shield: caldera_left
  - board: nice_nano_v2
    shield: caldera_right
  - board: nice_nano_v2
    shield: settings_reset

  # Souffle
  - board: nice_nano_v2
    shield: souffle_left
  - board: nice_nano_v2
    shield: souffle_right

  # TOTEM - https://github.com/GEIGEIGEIST/zmk-config-totem
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
    # there is no settingsreset (needed) for the XIAO
